#!/bin/sh
# This is a shell archive (produced by GNU sharutils 4.7).
# To extract the files from this archive, save it to some FILE, remove
# everything before the `#!/bin/sh' line above, then type `sh FILE'.
#
lock_dir=_sh01722
# Made on 2016-11-03 01:05 EDT by <n00803515@osprey.unfcsd.unf.edu>.
# Source directory was `/home/15/n00803515/compilersPrj5'.
#
# Existing files will *not* be overwritten, unless `-c' is specified.
#
# This shar contains:
# length mode       name
# ------ ---------- ------------------------------------------
#    253 -rw-r--r-- makefile
#   1580 -rw-r--r-- README.md
#   1311 -rw-r--r-- sql.l
#   2862 -rw-r--r-- sql.y
#
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=FAILED
locale_dir=FAILED
first_param="$1"
for dir in $PATH
do
  if test "$gettext_dir" = FAILED && test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir ;;
    esac
  fi
  if test "$locale_dir" = FAILED && test -f $dir/shar \
     && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
  then
    locale_dir=`$dir/shar --print-text-domain-dir`
  fi
done
IFS="$save_IFS"
if test "$locale_dir" = FAILED || test "$gettext_dir" = FAILED
then
  echo=echo
else
  TEXTDOMAINDIR=$locale_dir
  export TEXTDOMAINDIR
  TEXTDOMAIN=sharutils
  export TEXTDOMAIN
  echo="$gettext_dir/gettext -s"
fi
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
f=shar-touch.$$
st1=200112312359.59
st2=123123592001.59
st2tr=123123592001.5 # old SysV 14-char limit
st3=1231235901

if touch -am -t ${st1} ${f} >/dev/null 2>&1 && \
   test ! -f ${st1} && test -f ${f}; then
  shar_touch='touch -am -t $1$2$3$4$5$6.$7 "$8"'

elif touch -am ${st2} ${f} >/dev/null 2>&1 && \
   test ! -f ${st2} && test ! -f ${st2tr} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$1$2.$7 "$8"'

elif touch -am ${st3} ${f} >/dev/null 2>&1 && \
   test ! -f ${st3} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$2 "$8"'

else
  shar_touch=:
  echo
  ${echo} 'WARNING: not restoring timestamps.  Consider getting and'
  ${echo} 'installing GNU `touch'\'', distributed in GNU coreutils...'
  echo
fi
rm -f ${st1} ${st2} ${st2tr} ${st3} ${f}
#
if test ! -d ${lock_dir}
then : ; else ${echo} 'lock directory '${lock_dir}' exists'
  exit 1
fi
if mkdir ${lock_dir}
then ${echo} 'x - created lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to create lock directory `'${lock_dir}\''.'
  exit 1
fi
# ============= makefile ==============
if test -f 'makefile' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING makefile (file already exists)'
else
${echo} 'x - extracting makefile (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'makefile' &&
sql: sql.tab.c lex.yy.c
X	cc sql.tab.c -o p5
X	@echo "------------------------------------------"
X	@echo "Documentation in README.md file"
X	@echo "------------------------------------------"
sql.tab.c:sql.y
X	bison -vd sql.y
lex.yy.c: sql.l
X	flex -l sql.l
SHAR_EOF
  (set 20 16 11 03 01 03 23 'makefile'; eval "$shar_touch") &&
  chmod 0644 'makefile'
if test $? -ne 0
then ${echo} 'restore of makefile failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'makefile: MD5 check failed'
       ) << \SHAR_EOF
5694ae2cae1cc0cea9cfc538f194a70a  makefile
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'makefile'` -ne 253 && \
  ${echo} 'restoration warning:  size of makefile is not 253'
  fi
fi
# ============= README.md ==============
if test -f 'README.md' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING README.md (file already exists)'
else
${echo} 'x - extracting README.md (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'README.md' &&
# Project 5 - SQL Grammer with Flex and Bison
#### Nagavarun Kanaparthy
### Purpose
To demonstrate usage of the Flex and Bison to generate the SQL Parser Program.
It also help us for the Data Modeling Class here at UNF, since the final project
uses this project as assistance during classes between the year of 2014 to 2016.
### SQL Grammer
```
start
X        ::= expression
X
expression
X        ::= one-relation-expression | two-relation-expression
X
one-relation-expression
X        ::= renaming | restriction | projection
X
renaming
X        ::= term RENAME attribute AS attribute
X
term
X        ::= relation | ( expression )
X
restriction
X        ::= term WHERE comparison
X
projection
X        ::= term | term [ attribute-commalist ]
X
attribute-commalist
X        ::= attribute | attribute , attribute-commalist
X
two-relation-expression
X        ::= projection binary-operation expression
X
binary-operation
X        ::= UNION | INTERSECT | MINUS | TIMES | JOIN | DIVIDEBY
X
comparison
X        ::= attribute compare number
X
compare
X        ::= < | > | <= | >= | = | <>
X
number
X        ::= val | val number
X
val
X        ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
X
attribute
X        ::= CNO | CITY | CNAME | SNO | PNO | TQTY |
X                  SNAME | QUOTA | PNAME | COST | AVQTY |
X                  S# | STATUS | P# | COLOR | WEIGHT | QTY
X
relation
X        ::= S | P | SP | PRDCT | CUST | ORDERS
```
### Execution and Compiliation
```bash
make
X./p5 "Insert your file name here"
```
#### Flex Manual Compiliation
```bash
felx sql.l
```
#### Bison Manual Compiliation
```bash
bison sql.y
```
SHAR_EOF
  (set 20 16 11 02 14 32 57 'README.md'; eval "$shar_touch") &&
  chmod 0644 'README.md'
if test $? -ne 0
then ${echo} 'restore of README.md failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'README.md: MD5 check failed'
       ) << \SHAR_EOF
99a2a5f62e07ad78978bda5954bfe445  README.md
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'README.md'` -ne 1580 && \
  ${echo} 'restoration warning:  size of README.md is not 1580'
  fi
fi
# ============= sql.l ==============
if test -f 'sql.l' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING sql.l (file already exists)'
else
${echo} 'x - extracting sql.l (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 sql.l
M)7L*(VEN8VQU9&4@(G-Q;"YT86(N:"(*97AT97)N(&EN="!Y>6QV86P["F5X
M=&5R;B!I;G0@>7EL97@H=F]I9"D["B5]"D1E;&EM:71E<@E;(%QT70I7:&ET
M95-P86-E"7M$96QI;6ET97)]*PI,971T97()"5M!+5IA+7I="D1I9VET"0E;
M,"TY70HE)0I[5VAI=&53<&%C97T).PI[1&EG:71]*PD)>PH)"0D)"7EY;'9A
M;"`](&%T;VDH>7ET97AT*3L*"0D)"0ER971U<FX@=F%L.R`@(`H)"0D)?0HB
M/2()"0D)<F5T=7)N($5Q=6%L.PHB/"()"0D)<F5T=7)N($QE<W-4:&%N.PHB
M/B()"0D)<F5T=7)N($=R96%T97)4:&%N.PHB/#TB"0D)<F5T=7)N($QE<W-4
M:&%N17%U86P["B(^/2()"0ER971U<FX@1W)E871E<E1H86Y%<75A;#L*(CP^
M(@D)"7)E='5R;B!,97-S1W)E871E<CL*(B@B"0D)"7)E='5R;B!,969T4&5R
M.PHB*2()"0D)<F5T=7)N(%)I9VAT4&5R.PHB6R()"0D)<F5T=7)N($QE9G1"
M<F%C:V5T.PD*(ETB"0D)"7)E='5R;B!2:6=H=$)R86-K970["0HB>R()"0D)
M<F5T=7)N($QE9G1#=7)L>4)R86-K970["0HB?2()"0D)<F5T=7)N(%)I9VAT
M0W5R;'E"<F%C:V5T.PD*(BPB"0D)"7)E='5R;B!#;VUM83L*7&X)"0D)<F5T
M=7)N(#`["B)#3D\B"0D)<F5T=7)N($-.3SL)"B)#2519(@D)"7)E='5R;B!#
M2519.PD*(D-.04U%(@D)"7)E='5R;B!#3D%-13L)"B)33D\B"0D)<F5T=7)N
M(%-.3SL)"B)03D\B"0D)<F5T=7)N(%!.3SL)"B)44519(@D)"7)E='5R;B!4
M4519.PD*(E-.04U%(@D)"7)E='5R;B!33D%-13L)"B)154]402()"0ER971U
M<FX@455/5$$["0HB4$Y!344B"0D)<F5T=7)N(%!.04U%.PD*(D%64519(@D)
M"7)E='5R;B!!5E%463L)"B)3(R()"0ER971U<FX@4TYU;3L)"B)0(R()"0ER
M971U<FX@4$YU;3L)"B)#3TQ/4B()"0ER971U<FX@0T],3U(["0HB5T5)1TA4
M(@D)<F5T=7)N(%=%24=(5#L)"B)15%DB"0D)<F5T=7)N(%%463L)"B)53DE/
M3B()"0ER971U<FX@54Y)3TX["B))3E1%4E-%0U0B"0ER971U<FX@24Y415)3
M14-4.PHB34E.55,B"0D)<F5T=7)N($U)3E53.PHB5$E-15,B"0D)<F5T=7)N
M(%1)3453.PHB2D])3B()"0ER971U<FX@2D])3CL*(D1)5DE$14)9(@D)<F5T
M=7)N($1)5DE$14)9.PHB5TA%4D4B"0D)<F5T=7)N(%=(15)%.PHB4D5.04U%
M(@D)<F5T=7)N(%)%3D%-13L*(D%3(@D)"7)E='5R;B!!4SL*(E,B"0D)"7)E
M='5R;B!3.PHB4"()"0D)<F5T=7)N(%`["B)34"()"0ER971U<FX@4U`["B)0
M4D1#5"()"0ER971U<FX@4%)$0U0["B)#55-4(@D)"7)E='5R;B!#55-4.PHB
M3U)$15)3(@D)<F5T=7)N($]21$524SL*(E-405154R()"7)E='5R;B!35$%4
&55,["B4E
`
end
SHAR_EOF
  (set 20 16 11 02 16 55 03 'sql.l'; eval "$shar_touch") &&
  chmod 0644 'sql.l'
if test $? -ne 0
then ${echo} 'restore of sql.l failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'sql.l: MD5 check failed'
       ) << \SHAR_EOF
ce58554864421345f1d632e3b69e7ad3  sql.l
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'sql.l'` -ne 1311 && \
  ${echo} 'restoration warning:  size of sql.l is not 1311'
  fi
fi
# ============= sql.y ==============
if test -f 'sql.y' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING sql.y (file already exists)'
else
${echo} 'x - extracting sql.y (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 sql.y
M)7L*(VEN8VQU9&4@/'-T9&EO+F@^"F5X=&5R;B!Y>6QE>"@I.PHO+V5X=&5R
M;B!Y>71E>'0["B5]"B5S=&%R="!0<F]G<F%M"B5T;VME;B!%<75A;"!,97-S
M5&AA;B!'<F5A=&5R5&AA;B!,97-S1W)E871E<B!,97-S5&AA;D5Q=6%L($=R
M96%T97)4:&%N17%U86P*)71O:V5N($QE9G1097(@4FEG:'1097(@3&5F=$)R
M86-K970@4FEG:'1"<F%C:V5T($QE9G1#=7)L>4)R86-K970*)71O:V5N(%)I
M9VAT0W5R;'E"<F%C:V5T($-O;6UA($-.3R!#2519($-.04U%(%-.3R!03D\@
M0T]35"!44519(%-.04U%"B5T;VME;B!154]402!03D%-12!!5E%462!33G5M
M(%!.=6T@0T],3U(@5T5)1TA4(%%462!53DE/3B!)3E1%4E-%0U0@34E.55,*
M)71O:V5N(%1)3453($I/24X@1$E6241%0ED@5TA%4D4@4D5.04U%($%3(%,@
M4"!34"!04D1#5"!#55-4($]21$524R!35$%455,*)71O:V5N('9A;`HE)0I0
M<F]G<F%M("`@("`Z("`@97AP<F5S<VEO;GL@<')I;G1F*")!0T-%4%0B*3L@
M?3L*"F5X<')E<W-I;VX@(#H@("!O;F5296QA=&EO;D5X<')E<W-I;VX@>R!P
M<FEN=&8H(F5X<')E<W-I;VX@;VYE(')E;&%T:6]N(&5X<')E<W-I;VXB*3L@
M?3L*("`@("`@("`@("`@("`@('P@='=O4F5L871I;VY%>'!R97-S:6]N('L@
M<')I;G1F*")E>'!R97-S:6]N('1W;R!R96QA=&EO;B!E>'!R97-S:6]N(BD[
M('T["@IO;F5296QA=&EO;D5X<')E<W-I;VX@.B!R96YA;6EN9R![('!R:6YT
M9B@B;VYE(')E;&%T:6]N(&5X<')E<W-I;VX@<F5N86UI;F=<;B(I.R!].PH@
M("`@("`@("`@("`@("`@("`@("`@("!\(')E<W1R:6-T:6]N('L@<')I;G1F
M*")O;F4@<F5L871I;VX@97AP<F5S<VEO;B!R97-T<FEC=&EO;EQN(BD[('T[
M"B`@("`@("`@("`@("`@("`@("`@("`@('P@<')O:F5C=&EO;B![('!R:6YT
M9B@B;VYE(')E;&%T:6]N(&5X<')E<W-I;VX@<')O:F5C=&EO;EQN(BD[('T[
M"@IR96YA;6EN9R`Z("!T97)M(%)%3D%-12!A='1R:6)U=&4@05,@871T<FEB
M=71E('L@<')I;G1F*")R96YA;6EN9UQN(BD[('T["@IT97)M(#H@(')E;&%T
M:6]N>R!P<FEN=&8H(G1E<FU<;B(I.R!].PH@("`@("`@('P@3&5F=%!E<B!E
M>'!R97-S:6]N(%)I9VAT4&5R('L@?3L*"G)E<W1R:6-T:6]N(#H@("!T97)M
M(%=(15)%(&-O;7!A<FES;VX@>R!].PH*<')O:F5C=&EO;B`Z("`@('1E<FT@
M>WT[(`H@("`@("`@("`@("`@("`@?"!T97)M($QE9G1"<F%C:V5T(&%T=')I
M8G5T94-O;6UA;&ES="!2:6=H=$)R86-K970@>WT["@IA='1R:6)U=&5#;VUM
M86QI<W0@.B`@(&%T=')I8G5T92![('T[('P@871T<FEB=71E($-O;6UA(&%T
M=')I8G5T94-O;6UA;&ES=`H*='=O4F5L871I;VY%>'!R97-S:6]N(#H@<')O
M:F5C=&EO;B!B:6YA<GE/<&5R871I;VX@97AP<F5S<VEO;B![?3L*"F)I;F%R
M>4]P97)A=&EO;B`Z("`@54Y)3TX@>WT["B`@("`@("`@("`@("`@("`@("`@
M?"!)3E1%4E-%0U0@>WT["B`@("`@("`@("`@("`@("`@("`@?"!-24Y54R![
M?3L*("`@("`@("`@("`@("`@("`@("!\(%1)3453('M].PH@("`@("`@("`@
M("`@("`@("`@('P@2D])3B![?3L*("`@("`@("`@("`@("`@("`@("!\($1)
M5DE$14)9('M].PH*8V]M<&%R:7-O;B`Z("`@(&%T=')I8G5T92!C;VUP87)E
M(&YU;6)E<B![?3L*"F-O;7!A<F4@.B`@($QE<W-4:&%N('M].PH@("`@("`@
M("`@("!\($=R96%T97)4:&%N('M].PH@("`@("`@("`@("!\($QE<W-'<F5A
M=&5R('M].PH@("`@("`@("`@("!\($QE<W-4:&%N17%U86P@>WT["B`@("`@
M("`@("`@('P@1W)E871E<E1H86Y%<75A;"![?3L*("`@("`@("`@("`@?"!%
M<75A;"![?3L*"FYU;6)E<B`Z("`@('9A;"![?3L*("`@("`@("`@("`@?"!V
M86P@;G5M8F5R('M].PH*871T<FEB=71E(#H@0TY/('L@<')I;G1F*")!5%12
M24)55$5<;B(I.R!].PH@("`@("`@("`@("!\($-)5%D@>R!P<FEN=&8H(D%4
M5%))0E5415QN(BD[('T["B`@("`@("`@("`@('P@0TY!344@>R!P<FEN=&8H
M(D%45%))0E5415QN(BD[('T["B`@("`@("`@("`@('P@4TY/('L@<')I;G1F
M*")!5%1224)55$5<;B(I.R!].PH@("`@("`@("`@("!\(%!.3R![('!R:6YT
M9B@B05144DE"551%7&XB*3L@?3L*("`@("`@("`@("`@?"!44519('L@<')I
M;G1F*")!5%1224)55$5<;B(I.R!].PH@("`@("`@("`@("!\(%-.04U%('L@
M<')I;G1F*")!5%1224)55$5<;B(I.R!].PH@("`@("`@("`@("!\(%%53U1!
M('L@<')I;G1F*")!5%1224)55$5<;B(I.R!].PH@("`@("`@("`@("!\($-/
M4U0@>R!P<FEN=&8H(D%45%))0E5415QN(BD[('T["B`@("`@("`@("`@('P@
M05915%D@>R!P<FEN=&8H(D%45%))0E5415QN(BD[('T["B`@("`@("`@("`@
M('P@4TYU;2![('!R:6YT9B@B05144DE"551%7&XB*3L@?3L*("`@("`@("`@
M("`@?"!35$%455,@>R!P<FEN=&8H(D%45%))0E5415QN(BD[('T["B`@("`@
M("`@("`@('P@4$YU;2![('!R:6YT9B@B05144DE"551%7&XB*3L@?3L*("`@
M("`@("`@("`@?"!#3TQ/4B![('!R:6YT9B@B05144DE"551%7&XB*3L@?3L*
M("`@("`@("`@("`@?"!714E'2%0@>R!P<FEN=&8H(D%45%))0E5415QN(BD[
M('T["B`@("`@("`@("`@('P@4519('L@<')I;G1F*")!5%1224)55$5<;B(I
M.R!].PH*<F5L871I;VX@.B`@4R![?3L@?"!0('M].R!\(%-0('M].R!\(%!2
M1$-4('M].R!\($-54U0@>WT[('P@3U)$15)3('M].PHE)0HC:6YC;'5D92`B
M;&5X+GEY+F,B"FUA:6XH*7L*("`@('EY<&%R<V4H*3L*?0IY>65R<F]R*&-H
M87(J(&5R<F]R*7L*("`@('!R:6YT9B@B.B!E<G)O<B!F<F]M('EY97)R;W)<
M;B(I.PH@("`@<')I;G1F*"(E<UQN(BP@97)R;W(I.PI]"GEY=W)A<"@I>PH@
;("`@<')I;G1F*")I;B!Y>7=A<G!<;B(I.PI]
`
end
SHAR_EOF
  (set 20 16 11 02 17 03 44 'sql.y'; eval "$shar_touch") &&
  chmod 0644 'sql.y'
if test $? -ne 0
then ${echo} 'restore of sql.y failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'sql.y: MD5 check failed'
       ) << \SHAR_EOF
773299528e0904d35a94e86efdd19b05  sql.y
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'sql.y'` -ne 2862 && \
  ${echo} 'restoration warning:  size of sql.y is not 2862'
  fi
fi
if rm -fr ${lock_dir}
then ${echo} 'x - removed lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to remove lock directory `'${lock_dir}\''.'
  exit 1
fi
exit 0
